### ISSUE TITLE
NullPointerException APIGExporterMain.java:34

### ISSUE THREAD

**Issue by rikkouri** [isabinin/aws-apigateway-swagger-exporter#1]
Throwing a NullPointerException.

**Exception:**

``` bash
$ ./aws-api-export.sh --api XXXXXX
2015-12-09 20:02:38,748 ERROR - Error exporting API in Swagger format
java.lang.NullPointerException
    at com.bytecodestudio.apigexporter.APIGExporter.getResponseHeaders(APIGExporter.java:274)
    at com.bytecodestudio.apigexporter.APIGExporter.export(APIGExporter.java:141)
    at com.bytecodestudio.apigexporter.APIGExporterMain.execute(APIGExporterMain.java:59)
    at com.bytecodestudio.apigexporter.APIGExporterMain.main(APIGExporterMain.java:34)
```

**Env:**

``` bash
$ java -version
java version "1.7.0_91"
OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)

$ aws --version
aws-cli/1.9.12 Python/2.7.6 Linux/3.16.0-46-generic botocore/1.3.12

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"

$ uname -a
Linux ****** 3.16.0-46-generic #62~14.04.1-Ubuntu SMP Tue Aug 11 16:27:16 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by isabinin** [comment]
Should be fixed now. Please try the latest version.

**Comment by rikkouri** [comment]
Issues resolved. Working great! Thanks
